#!/bin/zsh

ROOT_PATH="/opt/attacks/attack-halo-backup/vps_manager/";
source /opt/attacks/attack-halo-backup/vps_manager/env;
BLUE='\033[0;34m'
GREEN='\033[0;32m'
CYAN='\033[0;35m'
RED='\033[0;31m'
YELLOW='\033[0;36m'
NC='\033[0m'
 
OS_T=$(cat << EOF | python2.7
import sys
print sys.platform
EOF
)

function usage {
    echo "  -l   list host in server.list"
    echo "  -L   see vpn's status"
    echo "  -u   upload a file to vpn"
    echo "  -e   excute shell in remote "
    echo "  -c   change vps install tool, exm: -c  , will sed -i s/yum/apt/ or reverse"
    echo "  -a   add a host to server.list "
    echo "  -R   set a rolse"
}

function list_vpn {
    vps-man vpn_status -R $1;
}

function up {
   echo  "fab -f  $ROOT_PATH/vpn-deploy.py $1";
   eval  "fab -f  $ROOT_PATH/vpn-deploy.py $1";
}

function exe {
   echo  "fab -f  $ROOT_PATH/vpn-deploy.py $1";
   eval  "fab -f  $ROOT_PATH/vpn-deploy.py $1";
}


function config_ipsec {

cat > /etc/ipsec.conf <<EOF
# ipsec.conf - strongSwan IPsec configuration file

# basic configuration

config setup
  # strictcrlpolicy=yes
  # uniqueids = no

# Add connections here.

# Sample VPN connections

conn %default
  ikelifetime=60m
  keylife=20m
  rekeymargin=3m
  keyingtries=1
  keyexchange=ikev1
  authby=secret
  ike=aes128-sha1-modp1024,3des-sha1-modp1024!
  esp=aes128-sha1-modp1024,3des-sha1-modp1024!

conn myvpn
  keyexchange=ikev1
  left=%defaultroute
  auto=add
  authby=secret
  type=transport
  leftprotoport=17/1701
  rightprotoport=17/1701
  right=$VPN_SERVER_IP
EOF

cat > /etc/ipsec.secrets <<EOF
: PSK "$VPN_IPSEC_PSK"
EOF

chmod 600 /etc/ipsec.secrets

}


function config_xl2tp {
cat > /etc/xl2tpd/xl2tpd.conf <<EOF
[lac myvpn]
lns = $VPN_SERVER_IP
ppp debug = yes
pppoptfile = /etc/ppp/options.l2tpd.client
length bit = yes
EOF

cat > /etc/ppp/options.l2tpd.client <<EOF
ipcp-accept-local
ipcp-accept-remote
refuse-eap
require-chap
noccp
noauth
mtu 1280
mru 1280
noipdefault
defaultroute
usepeerdns
connect-delay 5000
name $VPN_USER
password $VPN_PASSWORD
EOF

chmod 600 /etc/ppp/options.l2tpd.client

}




function start_vpn {
    KEY=$1;
    echo -n "server ip:"
    VPN_SERVER_IP=$(cat << EOF | python2
from configparser import ConfigParser
con = ConfigParser()
con.read("$ROOT_PATH/account.ini")
print con.get("$1".strip(), "Server IP")
EOF
)
    echo "$VPN_SERVER_IP";

    echo -n "ipsec psk:";
    VPN_IPSEC_PSK=$(cat << EOF | python2
from configparser import ConfigParser
con = ConfigParser()
con.read("$ROOT_PATH/account.ini")
print con.get("$1".strip(), "IPsec PSK")
EOF
)
    echo $VPN_IPSEC_PSK

    echo -n "user name:"
    VPN_USER=$(cat << EOF | python2
from configparser import ConfigParser
con = ConfigParser()
con.read("$ROOT_PATH/account.ini")
print con.get("$1".strip(), "Username")
EOF
)
    echo $VPN_USER;

    echo -n "password :"
    VPN_PASSWORD=$(cat << EOF | python2
from configparser import ConfigParser
con = ConfigParser()
con.read("$ROOT_PATH/account.ini")
print con.get("$1".strip(), "Password")
EOF
)
    echo $VPN_PASSWORD

    
    config_ipsec;
    if [ $? -eq 0 ];then
       echo "ipsec config ok";
    else
	    echo "ipsec config failed";
	    exit 1;
    fi
    config_xl2tp;

    if [ $? -eq 0 ];then
       echo "xl2tp config ok";
    else
	    echo "xl2tp config failed";
	    exit 1;
    fi
    
    mkdir -p /var/run/xl2tpd
    touch /var/run/xl2tpd/l2tp-control

    if [[ $OS_T == "darwin" ]];then
      xl2tpd restart
      ipsec start
    else
      service strongswan restart
      service xl2tpd restart
    fi


    # Ubuntu & Debian
    echo "$GREEN ============= info ===============";
    if [[ $(ipsec status | grep myvpn) == "" ]];then
    	ipsec up myvpn 
    else
	ipsec down myvpn && ipsec up myvpn
    fi
    if [ $? -eq 0 ];then
    else
	    exit 1;
    fi
    echo "============== end ===============$NC";
    #
    # # CentOS/RHEL & Fedora

    echo "c myvpn" > /var/run/xl2tpd/l2tp-control;
    VIA_IP=$(ip route | grep via | awk '{print $3}');
    echo -n "$BLUE # find default via $NC"
    echo "$YELLOW $VIA_IP";
    route add $VPN_SERVER_IP gw $VIA_IP;


    sleep 3
    ppp_dev="$(ifconfig| grep ^ppp | awk -F : '{print $1}')"
    echo "dev: $ppp_dev"
    if [[ $(ifconfig | grep $ppp_dev) == "" ]];then
        echo "$RED ppp0 vpn tunnel not connect successfuly!$NC"
    	route add default dev $ppp_dev
    fi
    echo "$BLUE add to route : $ppp_dev"
    route add default dev $ppp_dev
    echo "$NC"
#    route add default dev $ppp_dev
    test_pub_ip
}

function test_pub_ip {
    echo -n "public ip: $GREEN"
    wget -qO- http://ipv4.icanhazip.com; echo
    echo "$NC"
}

ROLS=""
RUN_EXE="";
EXE_ARG="";
RUN_UP="";
UP_ARG="";






ARGS=$@;
for p in $@;do
  if [[ $p == "help" ]];then
    usage;
  elif [[ $p == "fab" ]];then
    read -r  s <<< $@
    eval "vps-man  ${s[@]:3}"
    exit 0;
  break
  fi
done
while getopts "lhtR:s:ka:cL:ke:u:" arg ${ARGS} ; do
    if [[ "${arg}" = "?" ]]; then
      usage >&2;
    fi     
    case ${arg} in
      L) list_vpn $OPTARG;;
      l) vps-man list;;
      t) test_pub_ip;;
      k) 
	      route del default dev ppp0;
	      echo "d myvpn" > /var/run/xl2tpd/l2tp-control;
	      echo "$RED"
	      ipsec down myvpn ;
	      rm -rf /var/run/xl2tpd/l2tp-control;
	      echo "$NC"
	      route del $(ip route show | grep via | grep -v default | awk '{print $1}') ;;


      s) start_vpn $OPTARG;;
      e) 
	      RUN_EXE="11";
	      EXE_ARG=$OPTARG ;
	      exe $EXE_ARG;;
      u)      RUN_UP="11";
	      UP_ARG=$OPTARG ;
	      up $UP_ARG;
	      ;;
      R) ROLS=$OPTARG;;
      h) usage >&2;;
      c)   
  	 if [[ $(grep "apt-get" vpn-deploy.py) == "" ]];then
            sed -i 's/apt-get/yum/' vpn-deploy.py; 
         else
            sed -i 's/yum/apt-get/' vpn-deploy.py; 
         fi
      	;;    
      a)   
           PRO_NAME="$OPTARG";
         echo  $PRO_NAME  >> /opt/attacks/attack-halo-backup/vps_manager/server.list ;;
    esac   
done     

	echo "ROL " $ROLS;
	echo "Arg " $EXE_ARG;

